### ISSUE TITLE
Generator issue

### ISSUE THREAD

**Issue by scottmessinger** [jeffkreeftmeijer/navvy#8]
I'm getting a "load_missing_constant" issue when I try to use script/generate. I'm using ree-1.8.7-2010.02 and bundler. I'm also using navvy 0.3.2. Any idea what's going on?

Thanks in advance,
Scott

$ script/generate navvy --active_record
/Users/ScottMessinger/.rvm/gems/ree-1.8.7-2010.02@mongocc/gems/activesupport-2.3.9/lib/active_support/dependencies.rb:466:in `load_missing_constant': uninitialized constant Rails::Railtie (NameError)
    from /Users/ScottMessinger/.rvm/gems/ree-1.8.7-2010.02@mongocc/gems/activesupport-2.3.9/lib/active_support/dependencies.rb:106:in`const_missing'
    from /Users/ScottMessinger/.rvm/gems/ree-1.8.7-2010.02@mongocc/gems/navvy-0.3.2/lib/navvy.rb:27
    from /Users/ScottMessinger/.rvm/gems/ree-1.8.7-2010.02@mongocc/gems/activesupport-2.3.9/lib/active_support/dependencies.rb:182:in `require'
    from /Users/ScottMessinger/.rvm/gems/ree-1.8.7-2010.02@mongocc/gems/activesupport-2.3.9/lib/active_support/dependencies.rb:182:in`require'
    from /Users/ScottMessinger/.rvm/gems/ree-1.8.7-2010.02@mongocc/gems/activesupport-2.3.9/lib/active_support/dependencies.rb:547:in `new_constants_in'
    from /Users/ScottMessinger/.rvm/gems/ree-1.8.7-2010.02@mongocc/gems/activesupport-2.3.9/lib/active_support/dependencies.rb:182:in`require'
    from /Users/ScottMessinger/code/mongocc/config/initializers/navvy.rb:1

**Comment by aburets-sc** [comment]
Yeah. Have same problem but during server deployment using Mongrel:

ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:440:in `load_missing_constant': uninitialized constant
Rails::Railtie (NameError)
from ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:80:in`const_missing'
from ruby/lib/ruby/gems/1.8/gems/navvy-0.3.2/lib/navvy.rb:27
